ecommerce_profile:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'postgres') }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASSWORD') }}"         # 👈 Reads cleanly from your hidden .env file!
      port: 5432
      dbname: "{{ env_var('DB_NAME', 'airflow_metadata') }}"
      schema: public
      threads: 4
  target: dev